EXECUTABLE      := ant_world
SOURCES         := ant_world.cc render_mesh.cc route.cc world.cc 
LINK_FLAGS      := -lglfw -lGL -lGLU -lGLEW  -lopencv_core -lopencv_imgcodecs -lopencv_imgproc
CXXFLAGS	:= -pthread -Wall -Wpedantic
include $(GENN_PATH)/userproject/include/makefile_common_gnu.mk