EXECUTABLE      := simulator
SOURCES         := simulator.cc
LINK_FLAGS	:= -lopencv_core -lopencv_imgcodecs -lopencv_imgproc -lopencv_highgui

include $(GENN_PATH)/userproject/include/makefile_common_gnu.mk
