EXECUTABLE      := simulator
SOURCES         := simulator.cc
LINK_FLAGS      := -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_gpu
include $(GENN_PATH)/userproject/include/makefile_common_gnu.mk
